--- 
:users: 
- &id001 !ruby/object:User 
  address: a
  mail: a@a.lt
  name: a
  nickname: a
  number: "1"
  password: a
  player_points: 0
  surname: a
  team: &id003 !ruby/object:Team 
    active_team: []

    captain: *id001
    level_answers: []

    name: a
    number_of_games_played: 0
    passive_team: []

    players: 
    - *id001
    - &id002 !ruby/object:User 
      address: b
      mail: b@b.lt
      name: b
      nickname: b
      number: "2"
      password: b
      player_points: 0
      surname: b
    points: 0
- *id002
:games: []

:teams: 
- *id003
