--- 
:users: 
- &id003 !ruby/object:User 
  address: a
  mail: a
  name: a
  nickname: a
  number: a
  password: a
  player_points: 0
  surname: a
  team: &id002 !ruby/object:Team 
    active_team: []

    captain: &id001 !ruby/object:User 
      address: c
      mail: c@c.lt
      name: c
      nickname: c
      number: c
      password: c
      player_points: 0
      surname: c
      team: *id002
    level_answers: []

    name: alfa
    number_of_games_played: 0
    passive_team: []

    players: 
    - *id001
    - &id004 !ruby/object:User 
      address: b
      mail: b
      name: b
      nickname: b
      number: b
      password: b
      player_points: 0
      surname: b
      team: *id002
    - *id003
    points: 0
- *id004
- *id001
- !ruby/object:User 
  address: d
  mail: d@gmail.com
  name: d
  nickname: d
  number: d
  password: d
  player_points: 0
  surname: d
:games: 
- !ruby/object:Game 
  author: *id003
  available: true
  category: :real
  complexity: a
  forum: 
  - - lalalal
    - a
  - - i really did like a game
    - a
  - - so fun
    - a
  information: a
  levels: 
  - !ruby/object:Level 
    answer: "3"
    bonus: 0
    comment: add numbers
    level_name: first
    passed: false
    prompts: []

    task: 1+2
  name: a
  passed: []

  players: []

  won: 
- !ruby/object:Game 
  author: *id003
  available: true
  category: :real
  complexity: "1"
  forum: []

  information: let the game begin
  levels: []

  name: a
  passed: []

  players: []

  won: 
:teams: 
- !ruby/object:Team 
  active_team: []

  captain: *id004
  level_answers: []

  name: dogs&co
  number_of_games_played: 0
  passive_team: []

  players: 
  - *id004
  - *id003
  points: 0
- !ruby/object:Team 
  active_team: []

  captain: *id003
  level_answers: []

  name: cats
  number_of_games_played: 0
  passive_team: []

  players: 
  - *id003
  points: 0
- &id006 !ruby/object:Team 
  active_team: []

  captain: &id005 !ruby/object:User 
    address: c
    mail: c@c.gmail.com
    name: c
    nickname: c
    number: c
    password: c
    player_points: 0
    surname: c
    team: *id006
  level_answers: []

  name: horses
  number_of_games_played: 0
  passive_team: []

  players: 
  - *id005
  - *id003
  points: 0
- *id002
:messages: []

