--- 
:users: 
- &id001 !ruby/object:User 
  address: a
  mail: a
  name: a
  nickname: a
  number: a
  password: a
  player_points: 0
  surname: a
- !ruby/object:User 
  address: b
  mail: b
  name: b
  nickname: b
  number: b
  password: b
  player_points: 0
  surname: b
:games: 
- !ruby/object:Game 
  author: *id001
  available: true
  category: :real
  complexity: a
  forum: 
  - - lalalal
    - a
  information: a
  levels: []

  name: a
  passed: []

  players: []

  won: 
:teams: []

:messages: []

